---
- hosts: localhost
  tasks:
  - name: install apache
    apt:
      name: apache2
      state: latest
      update_cache: yes
  - name: virtualHost
    lineinfile:
      path: /etc/apache2/sites-available/000-default.conf
      regexp: '	DocumentRoot /var/www/html'
      line: '	DocumentRoot /var/www/web'
  - name: create web
    copy:
      src: web
      dest: /var/www/
      owner: www-data
      group: www-data
  - name: restart apache
    service: 
      name: apache2 
      state: restarted
